branches:
  pt: double
  eta: double
  cat_pT: int
  cat_eta: int
  # nSingleTracks: int
  # nTracks: int
  # nTracksAtVtx: int
  # nVTX: int
  # SV1: double
  # SV0: double
  # ip3d_pb: double
  # ip3d_pu: double
  # ip3d_pc: double
  # jfit_efrc: double
  # jfit_mass: double
  # jfit_sig3d: double
  # svp_mass: double
  # svp_efrc: double
  # energyFraction: double
  # mass: double
  # maxSecondaryVertexRho: double
  # maxTrackRapidity: double
  # meanTrackRapidity: double
  # minTrackRapidity: double
  # significance3d: double
  # subMaxSecondaryVertexRho: double
  # jfit_nvtx: int
  # jfit_nvtx1t: int
  # jfit_ntrkAtVx: int
  flavor_truth_label: int
  bottom: int
  charm: int
  light: int
binning:
  pt: [20, 30, 40, 50, 60, 75, 90, 110, 140, 200, 9999999]
  abs(eta): [0, 0.6, 1.2, 1.8, 2.5]
constraints:
  flavor_truth_label: [-1, 8]